version: '2'

services:
    mariadb:
        image: bitnami/mariadb:latest
        ports:
            - 3306:3306
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_DATABASE=splc2017

    phpMyAdmin:
        image: bitnami/phpmyadmin
        ports:
            - 90:80
        depends_on:
            - mariadb
        
    wordpress:
        image: bitnami/wordpress
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./wordpress_data:/bitnami
        depends_on:
            - mariadb
        environment:
            - MARIADB_HOST=mariadb
            - ALLOW_EMPTY_PASSWORD=yes
            - WORDPRESS_DATABASE_NAME=splc2017
            - WORDPRESS_DATABASE_USER=root
            - WORDPRESS_DATABASE_PASSWORD=''
